In [1]:
import pandas as pd

Function writen to skip through the entire database and select a portion. This is faster and more memory efficient that random sampling; however, this does not give an accurate representation of the data. This is was done to get a crude and broad representation of the data since it does not fit into memory.

In [2]:
file_path = "/app/data/bond_56_million_enriched.csv"

In [3]:
def SkipReader(file_path,n_rows_to_skip, n_rows_to_read, dtypes, col_names):
    #function to skip through csv and read
    
    temp_df = pd.read_csv(filepath_or_buffer=file_path,
                          header=0,
                          nrows=n_rows_to_read,
                          skiprows=n_rows_to_skip,
                          low_memory=False,
                          dtype=dtypes,
                          names=col_names)
    
    return temp_df

In [5]:
n_rows_to_read = 1000000
n_rows_to_skip = 6000000
chunk = n_rows_to_read + n_rows_to_skip

df = pd.read_csv(file_path, header=0, nrows=1000000, low_memory=False)

dtypes_dict = df.dtypes.apply(lambda x: x.name).to_dict()
column_names = list(df.columns)

for i in range(8):
    n_rows_to_skip = chunk * i
    
    df_to_concat = SkipReader(file_path,
                              n_rows_to_skip=n_rows_to_skip,
                              n_rows_to_read=n_rows_to_read,
                              dtypes=dtypes_dict,
                              col_names=column_names)
    
    df = pd.concat([df, df_to_concat])

In [22]:
dtype_dict = {'category': 'object',
 'categoryid': 'object',
 'client_id': 'object',
 'date': 'object',
 'detail_category': 'int64',
 'high_level_category': 'int64',
 'is_physical': 'bool',
 'recurring': 'float64',
 'address': 'object',
 'city': 'object',
 'country': 'object',
 'merchantemail': 'object',
 'latitude': 'float64',
 'merchantlogourl': 'object',
 'longitude': 'float64',
 'simple_description': 'object',
 'merchantphonenumber': 'object',
 'state': 'object',
 'merchanttype': 'object',
 'merchantwebsite': 'object',
 'zip_code': 'float64',
 'sourceid': 'float64',
 'transactionid': 'object',
 'uid': 'int64',
 'type': 'object',
 'subtype': 'object',
 'original_description': 'object',
 'amountnum': 'float64',
 'accountid': 'int64',
 'merchantname': 'object',
 'merchantcountry': 'object',
 'requestid': 'object',
 'created_at': 'object',
 'categorylabel': 'object',
 'originalmerchanturl': 'object',
 'cloudflaremerchanturl': 'object',
 'guid': 'object',
 'id': 'int64',
 'settlement': 'float64',
 'batch_request_id': 'object'}

In [9]:
type(df.columns)

pandas.core.indexes.base.Index

In [8]:
df.head()

,category,categoryid,client_id,date,detail_category,high_level_category,is_physical,recurring,address,city,...,merchantcountry,requestid,created_at,categorylabel,originalmerchanturl,cloudflaremerchanturl,guid,id,settlement,batch_request_id
0,Transfers,28,2dTNaeCfZo7c4xvAJVkFZexRdivzf7yN,2021-01-29T00:00:00.000Z,1170,10000015,True,NaN,NaN,NaN,...,US,f0f36b84-f70b-47e2-8715-be3f2c864966,2023-07-10 21:13:17.730,NaN,NaN,NaN,56c08cdc-b471-49ef-ba79-89587f3e4e98,481601,NaN,ce454fd1-828f-46a1-b8e6-cd708e8bd19d
1,Office Supplies,45,2dTNaeCfZo7c4xvAJVkFZexRdivzf7yN,2021-01-31T00:00:00.000Z,1177,10000007,False,NaN,NaN,NaN,...,NaN,f0f36b84-f70b-47e2-8715-be3f2c864966,2023-07-10 21:13:17.730,NaN,NaN,NaN,1265cf69-2e26-4886-98ae-ad8d9bfb35f5,481603,NaN,ce454fd1-828f-46a1-b8e6-cd708e8bd19d
2,Transfers,28,2dTNaeCfZo7c4xvAJVkFZexRdivzf7yN,2021-01-31T00:00:00.000Z,1170,10000015,False,NaN,NaN,NaN,...,US,f0f36b84-f70b-47e2-8715-be3f2c864966,2023-07-10 21:13:17.730,NaN,NaN,NaN,3f2fda47-152d-4842-8f3a-257b71eeabbb,481600,NaN,ce454fd1-828f-46a1-b8e6-cd708e8bd19d
3,Transfers,28,2dTNaeCfZo7c4xvAJVkFZexRdivzf7yN,2021-03-30T00:00:00.000Z,1170,10000015,False,NaN,NaN,NaN,...,US,f0f36b84-f70b-47e2-8715-be3f2c864966,2023-07-10 21:13:20.655,NaN,NaN,NaN,e4957a93-2861-4069-b281-b10847694300,485303,NaN,ce454fd1-828f-46a1-b8e6-cd708e8bd19d
4,Transfers,28,2dTNaeCfZo7c4xvAJVkFZexRdivzf7yN,2021-04-12T00:00:00.000Z,1170,10000015,False,NaN,NaN,NaN,...,US,f0f36b84-f70b-47e2-8715-be3f2c864966,2023-07-10 21:13:25.997,NaN,NaN,NaN,99c154b0-1a8d-43ca-9aee-5044e7960eeb,493221,NaN,ce454fd1-828f-46a1-b8e6-cd708e8bd19d

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000000 entries, 0 to 999999
Data columns (total 40 columns):
 #   Column                 Dtype
---  ------                 -----
 0   category               object
 1   categoryid             object
 2   client_id              object
 3   date                   object
 4   detail_category        int64
 5   high_level_category    int64
 6   is_physical            bool
 7   recurring              float64
 8   address                object
 9   city                   object
 10  country                object
 11  merchantemail          object
 12  latitude               float64
 13  merchantlogourl        object
 14  longitude              float64
 15  simple_description     object
 16  merchantphonenumber    object
 17  state                  object
 18  merchanttype           object
 19  merchantwebsite        object
 20  zip_code               float64
 21  sourceid               float64
 22  transactionid          object
 23  uid                    int64
 24  type                   object
 25  subtype                object
 26  original_description   object
 27  amountnum              float64
 28  accountid              int64
 29  merchantname           object
 30  merchantcountry        object
 31  requestid              object
 32  created_at             object
 33  categorylabel          object
 34  originalmerchanturl    object
 35  cloudflaremerchanturl  object
 36  guid                   object
 37  id                     int64
 38  settlement             float64
 39  batch_request_id       object
dtypes: bool(1), float64(7), int64(5), object(27)
memory usage: 2.7+ GB

In [7]:
df.isna().sum()

category                       0
categoryid                     0
client_id                      0
date                           0
detail_category                0
high_level_category            0
is_physical                    0
recurring                9000000
address                  7876518
city                     5564693
country                    87866
merchantemail            8886889
latitude                 7877540
merchantlogourl             3501
longitude                7877540
simple_description         36645
merchantphonenumber      7980454
state                    3428784
merchanttype                   0
merchantwebsite          8785084
zip_code                 7876513
sourceid                 9000000
transactionid                  0
uid                            0
type                           0
subtype                       14
original_description           1
amountnum                      0
accountid                      0
merchantname             2925621
merchantcountry            87866
requestid                      0
created_at                     0
categorylabel            3695197
originalmerchanturl      8999374
cloudflaremerchanturl    8999374
guid                           0
id                             0
settlement               9000000
batch_request_id               0
dtype: int64